---
- name: gather information from routers
  hosts: cisco
  gather_facts: no

  tasks:
    - name: gather router facts
      ios_facts:
      
    - name: display interfaces
      debug: 
        msg: "Interface {{ item.key }} has IP {{ item.value.ipv4.0.address }} / {{ item.value.ipv4.0.subnet }}"
      when: item.value.ipv4.0.address is defined
      with_dict: "{{ ansible_net_interfaces }}"
      loop_control:
        label: "{{ item.key }}"

    - name: display version
      debug:
        msg: "The IOS version is: {{ ansible_net_version }}"

    - name: display serial number
      debug:
        msg: "The serial number is:{{ ansible_net_serialnum }}"
