---
- name: CHANGE CONFIG SET ON IOS
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: RUN COMMAND
      ios_config:
        lines: "{{ tower_input | default('') }}"
        save_when: modified
      when: ansible_network_os == "ios"
      register: output

    - debug:
        msg: "{{ output }}"
