---
- name: restore router configurations
  hosts: routers
  gather_facts: no

  tasks:
  
    - name: get backup id to restore 
      set_fact:
        rollback_date: "{{ backup_id }}"
      when: backup_id is defined

    - name: load restore role
      include_role:
        name: restore
